const city = {
  nsk: 'Новосибирск',
  ekb: 'Екатеринбург',
  omsk: 'Омск',
}

const type = {
  residential:'Жилой',
  municipal: 'Муниципальные',
  commercial: 'Коммерческие'
}

const products = {
  mm6: 'Материал для виброшумоизоляции межэтажных перекрытий 6 мм',
  mm10: 'Материал для виброшумоизоляции межэтажных перекрытий 10 мм',
  mm8: 'Материал для виброшумоизоляции межэтажных перекрытий 8 мм',
}

export const data = [
  {
    id: 1,
    type: type.residential,
    city: city.nsk,
    name: 'Жилой дом на Гребенщикова (6/1)',
    product: products.mm10,
    volume: '10 000 м2',
    provider: 'Теплострой-НСК ООО',
    photo: '77-zhiloy-dom-na-grebenshikova-6-1-139.jpg',
  },
  {
    id: 2,
    type: type.residential,
    city: city.ekb,
    name: 'ЖК Татищевский',
    product: products.mm10,
    volume: '50 000 м2',
    provider: 'ЭнергоСфера ООО',
    photo: '48-zhk-tatishevskiy-27.jpg',
  },
  {
    id: 3,
    type: type.residential,
    city: city.omsk,
    name: 'Микрорайон Рябиновка',
    product: products.mm6,
    volume: '20 домов',
    provider: 'НСТ ООО',
    photo: '51-mikrorayon-ryabinovka-815.jpg',
  },
  {
    id: 4,
    type: type.residential,
    city: city.nsk,
    name: 'Жилой дом с административными помещениями',
    product: products.mm8,
    volume: '25 000 м2',
    provider: 'Теплострой-НСК ООО',
    photo: '76-zhiloy-dom-novosib-258.jpg',
  },
  {
    id: 5,
    type: type.municipal,
    city: city.ekb,
    name: 'Арбитражный суд',
    product: products.mm10,
    volume: '18 000 м2',
    provider: 'ЭнергоСфера ООО',
    photo: 'arbitrazhnyy-sud-18.jpg',
  },
  {
    id: 6,
    type: type.commercial,
    city: city.ekb,
    name: 'Аэропорт Кольцово',
    product: 'Материал для виброшумоизоляции межэтажных перекрытий 8 и 10 мм',
    volume: '15 500 м2',
    provider: 'ЭнергоСфера ООО',
    photo: '44-aeroport-koltsovo-612.jpg',
  },
  {
    id: 7,
    type: type.commercial,
    city: city.ekb,
    name: 'ТЦ Комсомолл',
    product: 'Материал для виброшумоизоляции межэтажных перекрытий 8 и 10 мм',
    volume: '3 000 м2, 2 500 м2',
    provider: 'ЭнергоСфера ООО',
    photo: '15-tts-komsomoll.jpg',
  },
  {
    id: 8,
    type: type.commercial,
    city: city.ekb,
    name: 'ТЦ Гринвич',
    product: products.mm8,
    volume: '1 000 м2',
    provider: 'ЭнергоСфера ООО',
    photo: '53-grinvich-573.jpg',
  },
  {
    id: 9,
    type: type.commercial,
    city: city.ekb,
    name: 'Отель Онегин',
    product: products.mm10,
    volume: '50 000 м2',
    provider: 'ЭнергоСфера ООО',
    photo: '62-otel-onegin-238.jpg',
  },
  {
    id: 10,
    type: type.commercial,
    city: city.ekb,
    name: 'ТЦ Антей',
    product: products.mm8,
    volume: '13 000 м2',
    provider: 'ЭнергоСфера ООО',
    photo: '19-antey-617.jpg',
  },
]